# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.3.0'

end
